export const theme = {
  light: {
    background: 'bg-white',
    text: 'text-gray-900',
    primary: 'bg-bronze-600',
    primaryHover: 'hover:bg-bronze-700',
    secondary: 'bg-gold-100',
    secondaryHover: 'hover:bg-gold-200',
    border: 'border-gray-200',
    card: 'bg-white',
    cardHover: 'hover:bg-gray-50',
    input: 'bg-white',
    inputBorder: 'border-gray-300',
    inputFocus: 'focus:border-bronze-600',
    button: 'bg-bronze-600 text-white',
    buttonHover: 'hover:bg-bronze-700',
    link: 'text-bronze-600',
    linkHover: 'hover:text-bronze-700',
  },
  dark: {
    background: 'bg-black',
    text: 'text-white',
    primary: 'bg-bronze-600',
    primaryHover: 'hover:bg-bronze-700',
    secondary: 'bg-black',
    secondaryHover: 'hover:bg-black',
    border: 'border-gray-800',
    card: 'bg-black',
    cardHover: 'hover:bg-black',
    input: 'bg-black',
    inputBorder: 'border-gray-800',
    inputFocus: 'focus:border-bronze-600',
    button: 'bg-bronze-600 text-white',
    buttonHover: 'hover:bg-bronze-700',
    link: 'text-gold-500',
    linkHover: 'hover:text-gold-400',
    section: 'bg-black',
    sectionAlt: 'bg-black',
    heading: 'text-white',
    subheading: 'text-gray-300',
    paragraph: 'text-gray-400',
    divider: 'border-gray-800',
    shadow: 'shadow-black',
    overlay: 'bg-black/90',
    backdrop: 'backdrop-blur-md',
    nav: 'bg-black/90',
    navBorder: 'border-gray-800',
    navText: 'text-white',
    navHover: 'hover:text-gold-500',
    footer: 'bg-black',
    footerText: 'text-gray-400',
    footerLink: 'text-gray-300 hover:text-gold-500',
    formLabel: 'text-gray-300',
    formInput: 'bg-black border-gray-800 text-white',
    formInputFocus: 'focus:border-bronze-600 focus:ring-bronze-600',
    formInputPlaceholder: 'placeholder-gray-500',
    formError: 'text-red-400',
    formSuccess: 'text-green-400',
    buttonOutline: 'border-gray-800 text-white hover:bg-black',
    buttonGhost: 'text-white hover:bg-black',
    buttonSecondary: 'bg-black text-white hover:bg-black',
    cardBorder: 'border-gray-800',
    cardShadow: 'shadow-black',
    tableHeader: 'bg-black text-white',
    tableRow: 'border-gray-800',
    tableCell: 'text-gray-300',
    badge: 'bg-black text-white',
    badgeSuccess: 'bg-green-900 text-green-200',
    badgeWarning: 'bg-yellow-900 text-yellow-200',
    badgeError: 'bg-red-900 text-red-200',
    tooltip: 'bg-black text-white',
    modal: 'bg-black border-gray-800',
    modalOverlay: 'bg-black/80',
    dropdown: 'bg-black border-gray-800',
    dropdownItem: 'text-white hover:bg-black',
    scrollbar: 'scrollbar-thumb-gray-800 scrollbar-track-black',
  },
} as const;

export type Theme = typeof theme; 